### PR TITLE
feature/readme

### PR DESCRIPTION
**Pull request by AchillesDougalis**
Changed readme files to .md files, and did some corrections.

### CODE REVIEW

**Review by cristianvasquez — COMMENTED** [review]
Hi @AchillesDougalis. The commit contains the binary of enterprise architect. Is this intended? if it is, what are the changes there?

**Comment by AchillesDougalis** [comment]
> Hi @AchillesDougalis. The commit contains the binary of enterprise architect. Is this intended? if it is, what are the changes there?

It was not intentional. I deleted it Thanks for the catch.

**Review by cristianvasquez — APPROVED** [review]
looks ok to me!

**Review by cristianvasquez — CHANGES_REQUESTED** [review]
This pull request is deleting the enterprise architect binary. This is not related to the specific issue.

If fixing this pull request is too cumbersome, you can add another one :)

**Pull request merged**
