### PR TITLE
Feature/4.2.0 rc.2

### PR DESCRIPTION
**Pull request by andreea-pasare**
- Fixed the following GitHub issues: 
  - #624 
  - #688 
  -  #689
  - #703
  - #705
- Modifications done at the level of the Enterprise Architect file:
  - Conventions used for both internal and external concepts (stored as tags in the CM): 
    - skos:historyNote: Contains the date that the concept was approved by the Working Group as a rdf:plainLiteral datatype using the following notation: “WG Approval DD/MM/YYYY”. For example, “WG Approval 28/04/20.”
    - skos:editorialNote: Contains the business term used by a specific data model that can be mapped to the concept. Its value is a rdf:plainLiteral datatype using the following notation: “Used by X BT/BG-Y, Z BT/BG-H..” where X and Z are the data models, and Y and H the number of the Business Term (BT) or Business Group (BG) that this concept represents. For example, “Used by eForms BT-724".
    - dct:source: Contains the reference from where this definition was taken.
  - Conventions used for external concepts.
    - For each external concept, the ‘Notes’ section of the Conceptual Model contains a hyperlink to a human-readable website that provides the original definition of the concept.

### CODE REVIEW

**Comment by cristianvasquez** [comment]
Hello, 

I'm still getting rewritten external vocabularies, is model2Owl well configured?

[redefined.ttl.txt](https://github.com/user-attachments/files/17812671/redefined.ttl.txt)

**Comment by cristianvasquez** [comment]
I found missing SHACL properties as well, is the Model2Owl config updated?

**Review by cristianvasquez — COMMENTED** [review]
- I can see the modifications in eA were applied as described
- The following github issues were addressed
	- #624
	- #688
	- #689
	- #703

I don't see the predicates removed:

- #705

**Comment by andreea-pasare** [comment]
> * I can see the modifications in eA were applied as described
> * The following github issues were addressed
>   
>   * [eforms BT-730 Subcontracting Value Known.  There does not seem to be a mapping in ePO to this #624](https://github.com/OP-TED/ePO/issues/624)
>   * [Remove predicate epo-sub:refersToOtherESPDResponse #688](https://github.com/OP-TED/ePO/issues/688)
>   * [Remove epo-con:ContractModificationInformation from core module diagram in ePO 4.2.0 #689](https://github.com/OP-TED/ePO/issues/689)
>   * [Revert  predicate epo-ful:refersToOrderLine cardinality to [0..1] #703](https://github.com/OP-TED/ePO/issues/703)
> 
> I don't see the predicates removed:
> 
> * [Remove Predicates from ePO 4.2.0 that were not forseen for 4.2.0 release #705](https://github.com/OP-TED/ePO/issues/705)

The predicates from #705 were removed, namely:
- `cccev:InformationRequirement epo:concernsLot epo:Lot` 
- `cccev:InformationRequirement epo:concernsLotGroup epo:LotGroup`
- `cccev:InformationRequirement epo:concernsProcedure epo:Procedure`

In epo_core.ttl file you can only see:
- `epo:LotAwardOutcome epo:concernsLot epo:Lot` 
- `epo:ProcurementProcessInformation epo:concernsProcedure epo:Procedure`.

**Pull request merged**
