### PR TITLE
fix: no external vocabularies

### PR DESCRIPTION
**Pull request by cristianvasquez**
fix: missing SHACL relations

### CODE REVIEW

**Comment by cristianvasquez** [comment]
I've run the script to remove the redefinition of external vocabularies and generated the SHACL from the enterprise architect file.

**Comment by andreea-pasare** [comment]
Some minor comments that should not have an impact from a technical point of view:

- I see some prefixes (related to rml) that are declared in the prefix section, but they are not used in the content part of the files.
- Also, in the owl:imports section, there are some namespaces that do not use prefixes even if we have them declared previously.
image

**Comment by andreea-pasare** [comment]
The namespaces for cpv and nuts should be manually changed. You can take those from a previous release candidate: [4.1.0-rc.2](https://github.com/OP-TED/ePO/blob/4.1.0-rc.2/implementation/ePO_core/shacl_shapes/ePO_core_shapes.rdf):
<sh:class rdf:resource="[http://data.europa.eu/nuts/scheme/2021"/>](http://data.europa.eu/nuts/scheme/2021%22/%3E)
<sh:class rdf:resource="[http://data.europa.eu/cpv/cpv"/>](http://data.europa.eu/cpv/cpv%22/%3E)
Changes should be reflected in **all RDF/TTL** shape files where these codelists are referenced.

**Comment by cristianvasquez** [comment]
> The namespaces for cpv and nuts should be manually changed. You can take those from a previous release candidate: [4.1.0-rc.2](https://github.com/OP-TED/ePO/blob/4.1.0-rc.2/implementation/ePO_core/shacl_shapes/ePO_core_shapes.rdf): <sh:class rdf:resource="[http://data.europa.eu/nuts/scheme/2021"/>](http://data.europa.eu/nuts/scheme/2021%22/%3E) <sh:class rdf:resource="[http://data.europa.eu/cpv/cpv"/>](http://data.europa.eu/cpv/cpv%22/%3E) Changes should be reflected in **all RDF/TTL** shape files where these codelists are referenced.

Thanks for the comments. Can you point out exactly what namespace needs to change?

**Comment by andreea-pasare** [comment]
Every mention of the following two:
<sh:class rdf:resource="http://publications.europa.eu/resource/authority/nuts"/>
<sh:class rdf:resource="http://publications.europa.eu/resource/authority/cpv"/>

Should be replaced by:
<sh:class rdf:resource="http://data.europa.eu/nuts/scheme/2021"/>
<sh:class rdf:resource="http://data.europa.eu/cpv/cpv"/>

These modifications should also be reflected in the TTL files.

**Pull request merged**
